services:
  db:
    image: mariadb:latest
    restart: always
    container_name: db
    environment:
      - MARIADB_DATABASE=web
      - MARIADB_ROOT_PASSWORD=qwer1234
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
